"""Add structured data to resumes

Revision ID: 881929221d25
Revises: da8b5f890b80
Create Date: 2026-08-19 01:06:05.935441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881929221d25'
down_revision: Union[str, None] = 'da8b5f890b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('extracted_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_data')
    op.drop_column('resumes', 'contact_phone')
    op.drop_column('resumes', 'contact_email')
    # ### end Alembic commands ###
