"""Expand jobs table

Revision ID: ceed2d00ac0a
Revises: 881929221d25
Create Date: 2026-08-20 00:48:03.186473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceed2d00ac0a'
down_revision: Union[str, None] = '881929221d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('salary_range', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source')
    op.drop_column('jobs', 'salary_range')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'employment_type')
    # ### end Alembic commands ###
