import { jsPDF } from 'jspdf';

const MARGIN = 48;
const PAGE_WIDTH = 612; // US Letter, points
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

/**
 * Render a learning plan (from /plans/job/:id or /plans/gap/:resumeId/:jobId)
 * to a PDF and trigger a real browser download - this is a normal web app,
 * not a sandboxed artifact, so a plain save-to-disk works.
 */
export function downloadPlanAsPdf(plan, filename) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  let y = MARGIN;

  const ensureSpace = (needed) => {
    if (y + needed > 792 - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const writeWrapped = (text, x, size, options = {}) => {
    doc.setFontSize(size);
    if (options.bold) doc.setFont(undefined, 'bold');
    else doc.setFont(undefined, 'normal');
    if (options.color) doc.setTextColor(...options.color);
    else doc.setTextColor(20, 20, 20);

    const lines = doc.splitTextToSize(text, CONTENT_WIDTH - (x - MARGIN));
    for (const line of lines) {
      ensureSpace(size * 1.4);
      doc.text(line, x, y);
      y += size * 1.35;
    }
  };

  // Header
  writeWrapped(plan.mode === 'gap' ? 'Skill Gap Learning Plan' : 'Role Learning Plan', MARGIN, 18, { bold: true });
  y += 2;
  writeWrapped(plan.target_label, MARGIN, 12, { color: [90, 90, 90] });
  y += 6;
  writeWrapped(
    `${plan.step_count} skill${plan.step_count === 1 ? '' : 's'} · ~${plan.total_estimated_weeks} week${plan.total_estimated_weeks === 1 ? '' : 's'} estimated`,
    MARGIN,
    11,
    { color: [90, 90, 90] }
  );
  y += 14;

  if (plan.message) {
    writeWrapped(plan.message, MARGIN, 12);
  }

  plan.steps.forEach((step, index) => {
    ensureSpace(40);
    y += 6;
    writeWrapped(`${index + 1}. ${step.skill}  (~${step.estimated_weeks} week${step.estimated_weeks === 1 ? '' : 's'})`, MARGIN, 13, { bold: true });
    writeWrapped(step.summary, MARGIN + 12, 10.5, { color: [60, 60, 60] });
    writeWrapped(step.why_it_matters, MARGIN + 12, 10, { color: [130, 130, 130] });
    y += 2;
    step.resources.forEach((resource) => {
      writeWrapped(`• ${resource.name} (${resource.type}): ${resource.url}`, MARGIN + 18, 10, { color: [40, 80, 180] });
    });
  });

  y += 16;
  ensureSpace(20);
  writeWrapped(
    `Generated by JobMatcher.io on ${new Date().toLocaleDateString()}. Estimates are rough guidance, not a guarantee.`,
    MARGIN,
    8.5,
    { color: [150, 150, 150] }
  );

  doc.save(filename);
}
